# Generated by Django 5.1.3 on 2024-12-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastAccuracy',
            fields=[
                ('accuracy_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('error_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accuracy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'forecast_accuracy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('forecast_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('forecast_year', models.TextField(blank=True, null=True)),
                ('forecast_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecast_date', models.DateField(blank=True, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'forecasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastTypes',
            fields=[
                ('type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=40)),
                ('type_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'forecast_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvincialNames',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'provincial_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('region_name', models.CharField(blank=True, max_length=30, null=True)),
                ('province', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonalForecasts',
            fields=[
                ('season_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('forecast_year', models.TextField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecast_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seasonal_forecasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherAlerts',
            fields=[
                ('alert_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_description', models.TextField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'weather_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('weatherdata_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observation_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherStations',
            fields=[
                ('station_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=15)),
                ('st_location', models.CharField(blank=True, max_length=25, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'weather_stations',
                'managed': False,
            },
        ),
    ]
